name 'kickinespresso'
maintainer 'KickinEspresso'
maintainer_email 'contact@kickinespresso.com'
license 'MIT'
description 'Installs/Configures a Rails development box.'
long_description 'Installs/Configures a Rails development box.'
version '0.1.1'
