#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', {}
cookbook 'build-essential'
cookbook 'omnibus_updater'

cookbook 'nodejs'
cookbook "git", {}
cookbook "postgresql", {}
cookbook "ruby_build", {:github=>"fnichol/chef-ruby_build", :ref=>"v0.7.2"}
cookbook "rbenv", {:github=>"fnichol/chef-rbenv"}
cookbook 'vim'
cookbook "redis", {:github=>"ctrabold/chef-redis"}
